/// Flutter icons GoodSleep
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GoodSleep
///      fonts:
///       - asset: fonts/GoodSleep.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class GoodSleep {
  GoodSleep._();

  static const _kFontFam = 'GoodSleep';

  static const IconData moon = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData moon_inv = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData moon_1 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData heartbeat = const IconData(0xf21e, fontFamily: _kFontFam);
  static const IconData bed = const IconData(0xf236, fontFamily: _kFontFam);
}
